### ISSUE TITLE
ImportError: No module named talib

### ISSUE THREAD

**Issue by andrei-nutas** [enigmampc/catalyst#187]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: windows 10
* Python Version: python 2.7
* Python Bitness: mean_reversion_simple exercise not working
* How did you install Catalyst: conda
* Python packages:

> alembic (0.9.6)
> backports.functools-lru-cache (1.4)
> bcolz (0.12.1)
> boto3 (1.5.20)
> botocore (1.8.34)
> Bottleneck (1.2.1)
> ccxt (1.10.774)
> certifi (2016.2.28)
> chardet (3.0.4)
> click (6.7)
> contextlib2 (0.5.5)
> cycler (0.10.0)
> cyordereddict (1.0.0)
> Cython (0.27.1)
> decorator (4.1.2)
> docutils (0.14)
> empyrical (0.2.1)
> enigma-catalyst (0.4.7)
> futures (3.2.0)
> idna (2.6)
> intervaltree (2.1.0)
> jmespath (0.9.3)
> Logbook (1.1.0)
> lru-dict (1.1.6)
> Mako (1.0.7)
> MarkupSafe (1.0)
> matplotlib (2.1.0)
> multipledispatch (0.4.9)
> networkx (2.0)
> numexpr (2.6.4)
> numpy (1.13.1)
> pandas (0.19.2)
> pandas-datareader (0.5.0)
> patsy (0.4.1)
> pip (9.0.1)
> pyparsing (2.2.0)
> python-dateutil (2.6.1)
> python-editor (1.0.3)
> pytz (2017.2)
> redo (1.6)
> requests (2.18.4)
> requests-file (1.4.2)
> requests-ftp (0.3.1)
> s3transfer (0.1.12)
> scipy (0.19.1)
> setuptools (36.4.0)
> six (1.11.0)
> sortedcontainers (1.5.7)
> SQLAlchemy (1.1.14)
> statsmodels (0.8.0)
> subprocess32 (3.2.7)
> tables (3.4.2)
> toolz (0.8.2)
> urllib3 (1.22)
> wheel (0.29.0)
> wincertstore (0.2)
> 

Now that you know a little about me, let me tell you about the issue I am
having:

Tried to run the mean_reversion_simple exercise and I was given the "ImportError: No module named talib". As a solution I tried searching on the web for how to install ta-lib and adapted it to work for the environment based on the code that I found in the instructions. I ran the following: pip install enigma-catalyst ta-lib==0.4.15

This is the result: 

> (catalyst) C:\Users\nutas\Desktop>pip install enigma-catalyst ta-lib==0.4.15
> Requirement already satisfied: enigma-catalyst in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages
> Collecting ta-lib==0.4.15
>   Downloading TA-Lib-0.4.15.tar.gz (715kB)
>     100% |################################| 716kB 664kB/s
> Requirement already satisfied: requests-file>=1.4.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: cyordereddict>=0.2.2 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: tables>=3.3.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: numpy>=1.13.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: requests>=2.9.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: decorator>=4.0.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: Cython>=0.25.2 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: lru-dict>=1.1.4 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: six>=1.10.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: bcolz<1,>=0.12.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: MarkupSafe>=0.23 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: pandas<0.20,>=0.19.2 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: empyrical<0.2.2,>=0.2.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: bottleneck>=1.0.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: boto3>=1.4.8 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: numexpr>=2.6.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: toolz>=0.8.2 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: scipy>=0.17.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: sqlalchemy>=1.0.8 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: contextlib2>=0.4.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: python-dateutil>=2.4.2 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: ccxt>=1.10.774 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: setuptools>36.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: pytz>=2016.4 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: patsy>=0.4.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: redo>=1.6 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: statsmodels>=0.6.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: networkx>=1.9.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: pip>=7.1.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: multipledispatch>=0.4.8 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: pandas-datareader>=0.2.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: Logbook>=0.12.5 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: sortedcontainers>=1.4.4 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: intervaltree>=2.1.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: click>=4.0.0 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: alembic>=0.7.7 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: Mako>=1.0.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from enigma-catalyst)
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from requests>=2.9.1->enigma-catalyst)
> Requirement already satisfied: idna<2.7,>=2.5 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from requests>=2.9.1->enigma-catalyst)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from requests>=2.9.1->enigma-catalyst)
> Collecting certifi>=2017.4.17 (from requests>=2.9.1->enigma-catalyst)
>   Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
>     100% |################################| 153kB 1.2MB/s
> Requirement already satisfied: botocore<1.9.0,>=1.8.34 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from boto3>=1.4.8->enigma-catalyst)
> Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from boto3>=1.4.8->enigma-catalyst)
> Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from boto3>=1.4.8->enigma-catalyst)
> Requirement already satisfied: requests-ftp in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from pandas-datareader>=0.2.1->enigma-catalyst)
> Requirement already satisfied: python-editor>=0.3 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from alembic>=0.7.7->enigma-catalyst)
> Requirement already satisfied: docutils>=0.10 in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from botocore<1.9.0,>=1.8.34->boto3>=1.4.8->enigma-catalyst)
> Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in c:\users\nutas\miniconda2\envs\catalyst\lib\site-packages (from s3transfer<0.2.0,>=0.1.10->boto3>=1.4.8->enigma-catalyst)
> Building wheels for collected packages: ta-lib
>   Running setup.py bdist_wheel for ta-lib ... error
>   Complete output from command C:\Users\nutas\Miniconda2\envs\catalyst\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\nutas\\appdata\\local\\temp\\pip-build-b8ewjs\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\nutas\appdata\local\temp\tmplpy4b8pip-wheel- --python-tag cp27:
>   c:\users\nutas\appdata\local\temp\pip-build-b8ewjs\ta-lib\setup.py:82: UserWarning: Cannot find ta-lib library, installation may fail.
>     warnings.warn('Cannot find ta-lib library, installation may fail.')
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-2.7
>   creating build\lib.win-amd64-2.7\talib
>   copying talib\abstract.py -> build\lib.win-amd64-2.7\talib
>   copying talib\deprecated.py -> build\lib.win-amd64-2.7\talib
>   copying talib\stream.py -> build\lib.win-amd64-2.7\talib
>   copying talib\test_abstract.py -> build\lib.win-amd64-2.7\talib
>   copying talib\test_data.py -> build\lib.win-amd64-2.7\talib
>   copying talib\test_func.py -> build\lib.win-amd64-2.7\talib
>   copying talib\test_stream.py -> build\lib.win-amd64-2.7\talib
>   copying talib\__init__.py -> build\lib.win-amd64-2.7\talib
>   running build_ext
>   skipping 'talib\_ta_lib.c' Cython extension (up-to-date)
>   building 'talib._ta_lib' extension
>   creating build\temp.win-amd64-2.7
>   creating build\temp.win-amd64-2.7\Release
>   creating build\temp.win-amd64-2.7\Release\talib
>   C:\Users\nutas\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\nutas\Miniconda2\envs\catalyst\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -IC:\Users\nutas\Miniconda2\envs\catalyst\include -IC:\Users\nutas\Miniconda2\envs\catalyst\PC /Tctalib\_ta_lib.c /Fobuild\temp.win-amd64-2.7\Release\talib\_ta_lib.obj
>   _ta_lib.c
>   talib\_ta_lib.c(524) : fatal error C1083: Cannot open include file: 'ta-libc.h': No such file or directory
>   error: command 'C:\\Users\\nutas\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
> 
>   ----------------------------------------
>   Failed building wheel for ta-lib
>   Running setup.py clean for ta-lib
> Failed to build ta-lib
> Installing collected packages: ta-lib, certifi
>   Running setup.py install for ta-lib ... error
>     Complete output from command C:\Users\nutas\Miniconda2\envs\catalyst\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\nutas\\appdata\\local\\temp\\pip-build-b8ewjs\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\nutas\appdata\local\temp\pip-fx_bgt-record\install-record.txt --single-version-externally-managed --compile:
>     c:\users\nutas\appdata\local\temp\pip-build-b8ewjs\ta-lib\setup.py:82: UserWarning: Cannot find ta-lib library, installation may fail.
>       warnings.warn('Cannot find ta-lib library, installation may fail.')
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-2.7
>     creating build\lib.win-amd64-2.7\talib
>     copying talib\abstract.py -> build\lib.win-amd64-2.7\talib
>     copying talib\deprecated.py -> build\lib.win-amd64-2.7\talib
>     copying talib\stream.py -> build\lib.win-amd64-2.7\talib
>     copying talib\test_abstract.py -> build\lib.win-amd64-2.7\talib
>     copying talib\test_data.py -> build\lib.win-amd64-2.7\talib
>     copying talib\test_func.py -> build\lib.win-amd64-2.7\talib
>     copying talib\test_stream.py -> build\lib.win-amd64-2.7\talib
>     copying talib\__init__.py -> build\lib.win-amd64-2.7\talib
>     running build_ext
>     skipping 'talib\_ta_lib.c' Cython extension (up-to-date)
>     building 'talib._ta_lib' extension
>     creating build\temp.win-amd64-2.7
>     creating build\temp.win-amd64-2.7\Release
>     creating build\temp.win-amd64-2.7\Release\talib
>     C:\Users\nutas\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\nutas\Miniconda2\envs\catalyst\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -IC:\Users\nutas\Miniconda2\envs\catalyst\include -IC:\Users\nutas\Miniconda2\envs\catalyst\PC /Tctalib\_ta_lib.c /Fobuild\temp.win-amd64-2.7\Release\talib\_ta_lib.obj
>     _ta_lib.c
>     talib\_ta_lib.c(524) : fatal error C1083: Cannot open include file: 'ta-libc.h': No such file or directory
>     error: command 'C:\\Users\\nutas\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
> 
>     ----------------------------------------
> Command "C:\Users\nutas\Miniconda2\envs\catalyst\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\nutas\\appdata\\local\\temp\\pip-build-b8ewjs\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\nutas\appdata\local\temp\pip-fx_bgt-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\nutas\appdata\local\temp\pip-build-b8ewjs\ta-lib\

## Reproduction Steps

explained above

## What steps have you taken to resolve this already?

explained above

# Anything else?

nothing

Sincerely,
Andrei Nutas

**Comment by ykgoon** [comment]
Isn't `talib` installed separately?

**Comment by treethought** [comment]
`ta-lib` is installed separately and not included in the requirements.txt. @andrei-nutas I believe you are receiving the error after running `pip install ta-lib` because you installed catalyst via Conda and not pip
Unfortunately it seems like you may need to build ta-lib yourself if you use Conda on windows.
The following issues may be helpful
https://github.com/mrjbq7/ta-lib/issues/156
https://github.com/mrjbq7/ta-lib/issues/127#issuecomment-309210268

You could alternatively try installing both catalyst and ta-lib using pip and a virtual environment

**Comment by swilso793** [comment]
I believe you have to install the underlying talib library either way. It doesn't come with pip. At least I had to install build it myself on Ubuntu 17.04

**Comment by andrei-nutas** [comment]
Thanks @treethought I'll first try to go at it again with Conda and build the ta-lib by myself, based on the links you have given me. If it doesn't work I will use pip, even though I'd rather not, since conda is a much friendlier environment.

**Comment by JimmyMVP** [comment]
TA-lib package in python is a wrapper of TA-lib library for technical analysis which is written in C as I understood it: https://www.ta-lib.org/. To get the wrapper to work you have to build the library in C first, this can be achieved in mac with brew by just doing brew install ta-lib, for linux/windows I am not sure, but in any case you can build it from the source code with cmake or make.

**Comment by andrei-nutas** [comment]
Found a solution that seems to work. Before installing catalyst I ran this: conda install -c quantopian ta-lib. Than after installing catalyst I went to C:\ProgramData\Miniconda2\pkgs\ta-lib-0.4.9-np111py27_0\Lib\site-packages (if you've installed everything in the default folders) and copy everything in the catalyst environment Lib: C:\ProgramData\Miniconda2\envs\catalyst\Lib. Now it seems to be working just need to set up the cote for my accounts.

**Comment by garichd** [comment]
Cheers Andrei.
This worked for me as well. Solution need to go in to Install tutorial.

**Comment by andrei-nutas** [comment]
Glad it helped garichd :D

**Comment by vcaldas** [comment]
Worked for me on OSX

brew install ta-lib
pip install ta-lib

Not sure why, but solved all problems I was having.

**Comment by DennyZen** [comment]
solved by myself! installed from https://www.lfd.uci.edu/~gohlke/pythonlibs

**Comment by zoakes** [comment]
I had trouble doing this initially, but after Catalina update in IOS I'm now unable to use ta-lib, tried brew install ta-lib, (get the error building wheel with gcc in pip install), Conda -c Quantopian version from above and still getting no module named talib when importing.  Please advise?  To hell with Catalina.

**Comment by seanrichmkv** [comment]
Though this issue is closed, I wanted to share this Medium article that worked like a charm for me, for any future travelers.

[https://medium.com/@keng16302/how-to-install-ta-lib-in-python-on-window-9303eb003fbb](url)
