### ISSUE TITLE
Live and Backtest data for the same period significantly different for eth_usdt on Poloniex

### ISSUE THREAD

**Issue by brinew27** [enigmampc/catalyst#230]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: Python 2.7.13 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda initiall, pip re-install to update
* Python packages: 

```
alembic                   0.9.6                     <pip>
attrdict                  2.0.0                     <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
boto3                     1.5.22                    <pip>
botocore                  1.8.36                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h94faf87_0
ccxt                      1.10.1063                 <pip>
certifi                   2016.2.28                py27_0
certifi                   2018.1.18                 <pip>
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.2                     <pip>
eth-abi                   1.0.0b0                   <pip>
eth-account               0.1.0a2                   <pip>
eth-keyfile               0.5.0                     <pip>
eth-keys                  0.2.0b1                   <pip>
eth-rlp                   0.1.0a2                   <pip>
eth-utils                 1.0.0b1                   <pip>
futures                   3.2.0                     <pip>
git                       2.16.1                        0
hexbytes                  0.1.0b0                   <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
jmespath                  0.9.3                     <pip>
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mkl                       2017.0.3                      0
multipledispatch          0.4.9                     <pip>
networkx                  2.0                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0
openssl                   1.0.2l            vc9hb274bc6_5  [vc9]
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
patsy                     0.4.1                     <pip>
pip                       9.0.1                    py27_1
pycryptodome              3.4.11                    <pip>
pyparsing                 2.2.0                     <pip>
pysha3                    1.0.2                     <pip>
python                    2.7.13              h1b6d89f_16
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.2                    <pip>
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scikit-learn              0.19.1                    <pip>
scipy                     0.19.1              np113py27_0
setuptools                36.4.0                   py27_1
six                       1.11.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                    vc9_1  [vc9]
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
TA-Lib                    0.4.16                    <pip>
tables                    3.4.2                     <pip>
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.2                     <pip>
urllib3                   1.22                      <pip>
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
web3                      4.0.0b9                   <pip>
wheel                     0.29.0                   py27_0
wincertstore              0.2              py27hf04cefb_0
zlib                      1.2.11               hbc2faf4_2
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

My catalyst algorithm has been performing very well in backtest, but horribly in live mode. I tried to isolate the issue by seeing if it was making the same trading decisions for the same time period in backtest vs live. I did this by live trading a period of time, saving the performance csv (custom_signals_stats.csv), then waiting until the backtest data was available for that period, and performing a backtest over that same day, using the exact same trading code, then saving that performance csv separately and comparing.

I've attached portions of the two csv files to compare. 

EDIT: Apparently I can't attach CSVs, so here are links to my Google Drive to download them:

Backtest csv: https://goo.gl/1vq5gK
Live csv: https://goo.gl/GJZsrq

I immediately noticed a few things. Price seemed to be staggered by one minute, but while it tracked generally between the two files, it was only about 50% matching. I also noticed my algorithm's trade logic (pricerise in the files) was wildly different. That led me to compare a few of the other numbers and realized nearly every calculation coming from TALib was significantly different. Most shockingly was the huge discrepancy in the trade volume. In the live trading, it was showing a consistent volume of around 13000, but in the backtest it was jumping around between 76000, 2000 and 45 within just a 10 minute time frame. the Obv indicator was also significantly different

My algorithm involves training a machine learning algorithm using a singificant amount of backtest gathered data and indicators, so this mismatch between backtest and live data being fed to my algorithm started to help make sense of why it performed so differently between the two settings.

Here are my settings for the main catalyst algorithm which I used to generate these two files:

```
        if live:
            run_algorithm(
                capital_base=100,
                initialize=initialize,
                handle_data=handle_data,
                analyze=analyze,
                exchange_name='poloniex',
                live=True,
                algo_namespace=NAMESPACE,
                base_currency='usdt',
                live_graph=False,
                simulate_orders=False,
                stats_output=None,
            )

        else:
            folder = os.path.join(
                tempfile.gettempdir(), 'catalyst', NAMESPACE
            )
            ensure_directory(folder)

            timestr = time.strftime('%Y%m%d-%H%M%S')
            out = os.path.join(folder, '{}.p'.format(timestr))
            # catalyst run -f catalyst/examples/mean_reversion_simple.py \
            #    -x bitfinex -s 2017-10-1 -e 2017-11-10 -c usdt -n mean-reversion \
            #   --data-frequency minute --capital-base 10000
            run_algorithm(
                capital_base=100,
                data_frequency='minute',
                initialize=initialize,
                handle_data=handle_data,
                analyze=analyze,
                exchange_name='poloniex',
                algo_namespace=NAMESPACE,
                base_currency='usdt',
                start=pd.to_datetime('2018-2-09', utc=True),
                end=pd.to_datetime('2018-2-09', utc=True),
                output=out
            )
            log.info('saved perf stats: {}'.format(out))
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

I'm hoping that if you were to execute a series of live actions against poloniex eth_usdt and a backtest using bundle data you should see something similar.
...

## What steps have you taken to resolve this already?

Illustrated above.
...

# Anything else?

...

Sincerely,
Darthus

**Comment by fredfortier** [comment]
Investigating now.

**Comment by fredfortier** [comment]
@brinew27 are you able to recreate these files easily? If you so, would be able to upgrade to 0.5.3 and regenerate the backtest file? The related fix should correct the price data issue. I'll look into the volume issue more specifically now.

**Comment by fredfortier** [comment]
To track steps towards resolving this issue, here is the unit test which we are using to compare bundles against exchange data: tests.exchange.test_suites.test_suite_bundle.TestSuiteBundle#test_validate_bundles. It's selecting a random sample of exchanges (here we are forcing Poloniex) and a random sample for markets within that exchange. Here we are comparing the `close` price only, adjusting to include volume.

To be clear, we are comparing data received directly from the "OHLCV" api of Poloniex to data resampled from the bundles using the same timeframes. Since Poloniex, does not offer minute-level OHLCV, the bundles have been calculated in advance based on the trade data. There are small differences between these values which seem like rounding differences but I do not know how exactly Poloniex calculate their candles.

```
comparing close for poloniex/['dash_xmr', 'fldc_btc', 'fct_btc'] with 30T timeframe until 2018-02-11 00:03:00+00:00
the bundle first / last row:
                           TradingPair(4449 [fct_btc])  TradingPair(243867 [dash_xmr])  TradingPair(565587 [fldc_btc])
2018-02-11 00:00:00+00:00                   0.00319248                       2.5438652                      0.00000290
2018-02-10 19:00:00+00:00                   0.00320277                       2.4868801                      0.00000298
the exchange first / last row:
                           TradingPair(4449 [fct_btc])  TradingPair(243867 [dash_xmr])  TradingPair(565587 [fldc_btc])
2018-02-11 00:03:00+00:00                   0.00313807                      2.54373267                      0.00000290
2018-02-10 19:33:00+00:00                   0.00317501                      2.49650100                      0.00000294
```

Investigating further.

**Comment by fredfortier** [comment]
The volumes also seem to match except for the last candle which understand why. When resampling, we are labeling each timeframe with the left value. This allows us to include the trailing transactions (in this case between 2018-02-11 00:00:00 and 2018-02-11 00:03:00+00:00) without having the last candle in the future. The calculated start date based on the end date, 3 candles and a 30T interval is: 2018-02-10 22:33:00+00:00 which would fit in a 4th candle labeled 2018-02-10T22:30:00. We can choose to include (which 0.5.3 does) or remove it. Personally, I'd remove it because it's not intuitive to get 4 candles when requesting 3. Poloniex avoids this issue by using variable times, but most other exchanges use fixed times like Catalyst. This discrepancy is going to throw off your TA indicators if you are using all candles returned from history. It won't if you don't use the last candle.

```
comparing volume for poloniex/['xrp_usdt', 'btcd_btc', 'storj_btc'] with 30T timeframe until 2018-02-11 00:03:00+00:00
Backend TkAgg is interactive backend. Turning interactive mode on.
the bundle data:
                           TradingPair(223765 [storj_btc])  TradingPair(345380 [xrp_usdt])  TradingPair(430706 [btcd_btc])
2018-02-10 23:00:00+00:00                       1.35452027                 370759.90731357                      0.00000000
2018-02-10 23:30:00+00:00                       0.55846152                 474921.72183441                      0.02663262
2018-02-11 00:00:00+00:00                       0.01046678                  37824.48576019                      0.00061182
the exchange data:
                           TradingPair(223765 [storj_btc])  TradingPair(345380 [xrp_usdt])  TradingPair(430706 [btcd_btc])
2018-02-10 23:03:00+00:00                       1.35452047                 370759.90731546                      0.00000000
2018-02-10 23:33:00+00:00                       0.55846189                 474921.72183611                      0.02663269
2018-02-11 00:03:00+00:00                       0.06212471                 894650.16073150                      0.04000684
```

Now that we've established this, I'll investigate more closely based on your spreadsheets. Let me know when you have a chance to update your backtest to 0.5.3.

**Comment by brinew27** [comment]
Hey @fredfortier, thanks for looking into this.

For reference, I am using this to get price data for my TAlib indicators:

```
prices = data.history(
        symbol('eth_usdt'),
        fields=['price', 'open', 'high', 'low', 'close', 'volume'],
        bar_count=50,
        frequency="15T"
    )

indicators['willr'] = talib.WILLR(prices.high.as_matrix(), prices.low.as_matrix(), prices.close.as_matrix(), 14)
```

Are you saying that based on the way Poloniex bundle data is processed (and whether or not it includes the last candle), that I will be processing different data for the willr (in this case) for a given frame (say at current price 837) will be different in live vs backtest because of which candles it's using? Is there a way for me to make this consistent?

I'm running my algo live right now using 0.5.3 and will let it run for a few hours, then will pull down the backtest data this evening when the bundles are updated and prepare them for comparison and upload probably tomorrow evening (PST).

Thanks again for helping troubleshoot, my data needs to be very very close between live and backtest for any sort of ML based algorithm to function well.

**Comment by fredfortier** [comment]
Yes, there are some diffs because we are fetching candles directly in live vs computing them from minute data in backtest. 

The diffs should be very minor (see the unit test results above generated from random samples). Unless you think otherwise, I don't see these differences affecting a TA indicators enough tip the scale on any trading decision. 

To be 100% consistent, you could use 1T candles and resample them. Unfortunately, this won't work with poloniex because it does not offer 1T frequency. We're working on another feature which computes candles from trades. The goal isn't directly to address these small differences but to offer live historical data for exchanges which have a Trades api but not an OHLCV api.

I feel like 0.5.3 is likely to resolve the issue which your reported but it's possible that I'm missing something.

**Comment by brinew27** [comment]
@fredfortier, Alright, I've gathered a couple hours of live trading (it errorred out due to the open orders issue), but hopefully this is enough for comparison, as I've grabbed the backtest data for comparison. This is using 0.5.3 with cleaned and re-downloaded Poloniex exchange data just as of about 30 mins ago.

Live: https://goo.gl/Yhnhvo
Backtest: https://goo.gl/hczaf8

Prices look generally the same, and most of the indicators do too, but there are still discrepancies that jump out every 4 or 5 minutes. For example "21:47:00" in the backtest file has a price of 867, whereas the analogous "21:48:00" (still not clear why they're 1 minute staggered, is one open while the other is close?), is 870.355589 in live.

And the Volume issue remains, for the entire about 1.5 hours in live the volume is in the 7000s, whereas in backtest it jumps all over. I actually feel like the backtest seems more realistic, as looking at the poloniex price charts I see a spike in volume around 21:50, but it dying down after. Though the backtest sheet has 4 or 5 minute spans with 0 volume, which seems odd.

Hope this helps.

**Comment by fredfortier** [comment]
Thanks for the update. I’m investing the volume issue further.

**Comment by fredfortier** [comment]
@lenak25 would you be able to follow up on this. See the test which I ran which seem to display the correct volume value versus what @brinew27 experiences in his algorithm.

**Comment by lenak25** [comment]
Sure, I am looking at it.

**Comment by lenak25** [comment]
@brinew27 , after having another look with @fredfortier and @AvishaiW on the volume unit-test results earlier, we do see meaningful differences in volume between the bundles and the Poloniex OHLCV fetched directly candles. We are continuing to investigate this.

**Comment by lenak25** [comment]
Hi @brinew27, I investigated the volume issue using our unit-test (tests.exchange.test_suites.test_suite_bundle.TestSuiteBundle#test_validate_bundles) @fredfortier has mentioned earlier which compares the data bundles to the fetched candles directly from the exchange.
It seems that Poloniex is using the same fixed time intervals as catalyst and other exchanges do (meaning for 5T is uses :00, :05, :10 etc) HOWEVER when the data is fetched, the timestamp which is given to it depends on the requested timestamp (meaning: if a non fixed timestamp will be requested, a non fixed timestamp will be used for indexing data calculated for the fixed time interval).
Here is an example:
```
comparing volume for poloniex/[u'eth_usdt'] with 15T timeframe until 2018-02-13 00:03:00+00:00
the bundle data:
                           TradingPair(23347 [eth_usdt])
2018-02-12 22:00:00+00:00                 19878.49964244
2018-02-12 22:15:00+00:00                 85794.28419550
2018-02-12 22:30:00+00:00                 11932.44009731
2018-02-12 22:45:00+00:00                 16487.80567038
2018-02-12 23:00:00+00:00                 33189.33097604
2018-02-12 23:15:00+00:00                 50434.38112109
2018-02-12 23:30:00+00:00                 43795.19235418
2018-02-12 23:45:00+00:00                 38122.87638094
2018-02-13 00:00:00+00:00                 45902.69842496
the exchange data:
                           TradingPair(23347 [eth_usdt])
2018-02-12 22:03:00+00:00                 19878.49964262
2018-02-12 22:18:00+00:00                 85794.28419580
2018-02-12 22:33:00+00:00                 11932.44009749
2018-02-12 22:48:00+00:00                 16487.80567053
2018-02-12 23:03:00+00:00                 33189.33097650
2018-02-12 23:18:00+00:00                 50434.38112133
2018-02-12 23:33:00+00:00                 43795.19235434
2018-02-12 23:48:00+00:00                 38122.87638150
2018-02-13 00:03:00+00:00                 45902.69842534
```
As you can see, the values of the two tables are matching.  The first table includes the bundles data which was resampled from minute data (comprised from the trading, as Poloniex does not support a 1 min resolution). The second table includes candles fetched directly from Poloniex. So, it is clear that the values are matching, however the timestamps are not. 
And in addition, we get FUTURE data. Meaning, when we requested data from Poloinex, we requested till 00:03:00, so the last candle that starts from 00:00:00 and ends at 00:14:59 should not appear at the second table (it appears at the first, because I've explicitly wanted to look at "future" bundles as well) but it is also returned from Poloniex.

**Comment by lenak25** [comment]
Well, correction: Poloniex does not alter the timestamps, it must be an issue with the unit test. 
But it is indeed brings the last candle from the future (although the end data requested is 00:03, the candle of 00:00 is still returns). Continue to investigate.

**Comment by brinew27** [comment]
@lenak25 Thanks for looking into this. I'm curious how the bundle coming from the future would affect backtest vs live test performance, unless you're sure that's because of your unit test?

As for how I got the volumes shown, I am simply using these two lines of code in my handle data to get and record the volume:

```
current = data.current(symbol('eth_usdt'), fields=['close', 'volume'])

record(
        volume=current['volume']
)
```

And I am using this configuration to run live against Poloniex:

```
        if live:
            run_algorithm(
                capital_base=100,
                initialize=initialize,
                handle_data=handle_data,
                analyze=analyze,
                exchange_name='poloniex',
                live=True,
                algo_namespace=NAMESPACE,
                base_currency='usdt',
                live_graph=False,
                simulate_orders=False,
                stats_output=None,
            )
```

The only thing I change to backtest is using this configuration:

```
run_algorithm(
                capital_base=100,
                data_frequency='minute',
                initialize=initialize,
                handle_data=handle_data,
                analyze=analyze,
                exchange_name='poloniex',
                algo_namespace=NAMESPACE,
                base_currency='usdt',
                start=pd.to_datetime('2018-2-12', utc=True),
                end=pd.to_datetime('2018-2-12', utc=True),
                output=out
            )
```

Live gives me the oddly consistent volume as shown in my CSV, backtest gives me more erratic (and seemingly correct) volumes. I can send along my code file if that'll help catch the issue.

**Comment by lenak25** [comment]
Thanks for the info @brinew27.
I will continue trying to reconstruct using these inputs. If more information will be needed, I will let you know.
Thanks!

**Comment by lenak25** [comment]
Hi @brinew27, I was able to reconstruct and see the difference in volume you have witnessed. This is basically a result of the different way in which data is retrieved in live vs backtest.
In backtest, the data is read from bundles, which are organized in 1 minute candles, meaning that for each minute you have an OHLCV information from the past.

In live, the data is fetched directly from the exchange. 
If you request `data.current` you get the ticker information from the exchange. The volume field contains the 24 hour volume (that's why in your data sheet you had a volume which looked quite "static"). 
You are also able to get OHLCV information live, but that depends on the exchange. Poloniex, as mentioned above, has a minimal resolution of 5 min candles (meaning 1 min candles are not possible live). Candle information is accessible via `data.history`.

Hope things are more clearer, please let me know if you have any more questions.

**Comment by gatapia** [comment]
I have also been able to reproduce this after investigating poor performance of my algo in live mode.

During backtest I get my data using `data.history(symbols, ['close', 'volume'], bar_count=2, frequency='5T').tail(1)` (see #236 for explanation of `tail(1)`).  However, after reading @fredfortier description about the last candle being unreliable in `live=True` mode I created an algo that gets 3 bars and logs them out for investigation purposes.

So I have a CSV with the backtest data (using last frame of data.history(freq='5T')) and I have a CSV with 1 day of live data logging 2 candles at freq='5T'.  Note: I am not using `data.current`, just `data.history`.  I also round the live data to nearest 5 minutes to better compare with backtest data.  I have about 180 rows that overlap in both datasets which I use for the comparison.

First thing I noticed that getting `bar_count=2` returns 2 or **3** candles arbitrarily.  Also described in #236. Let's ignore this for now.

If I compare the volumes of backtest vs **last** candle of live `data.history` I get this distribution:
![image](https://user-images.githubusercontent.com/135965/36502153-18a36252-179d-11e8-8244-2966bc5ba4c0.png)

So we can already see that these are different distributions, even though the periods plottted are overlapping periods.
![image](https://user-images.githubusercontent.com/135965/36502175-2f5232f8-179d-11e8-96ff-1f3dfdec067a.png)

You can see close price tracking nicely but volumes are all over the place with the difference (volume_perc) column being out by several hundred percent.

So now if I take the second last candle, knowing that the last candle can be compromised as per @fredfortier comment, we get the following distribution:

![image](https://user-images.githubusercontent.com/135965/36501927-943af9e4-179c-11e8-8dfe-6c2cac01c320.png)

This time the distribution looks good but digging into the data we still see huge variations:
![image](https://user-images.githubusercontent.com/135965/36502251-77298900-179d-11e8-9040-ad93086825d2.png)

I appreciate that backtest data is built from 1 minute candles and can be resampled into nice 5 minute chunks but there must be a way to get a similar 'last 5 minute' volume information from live exchanges.

**Comment by fredfortier** [comment]
@lenak25 <https://github.com/lenak25> based on your comment above, is there
a solution to the Poloniex volume being off like this? I understand that it
is the value which comes back when querying Poloniex but have you found the
culprit.

**Comment by lenak25** [comment]
Hi @gatapia,

As mentioned above, we have compared the data retrieved from the bundles to the data fetched live from the exchanges and didn't observe any dramatic differences.
The only thing that was observed is that when requesting **historical** data then there is a differences in the way data is retrieved from bundles vs exchanges. If we request 5-min candles with an end date of 00:03 then Poloniex for example will return the entire last candle which started at 00:00:00, meaning data representing 00:00:00-00:04:59 will be returned. While in the bundles case, when we request data with an end date of 00:03 then the last candle returned will be proportional (00:00:00-00:02:59).
If you feel that we missed something and that there are indeed some mismatches, please share the code you have run so we could have a better understanding of what you observed.

Thanks,
Lena

**Comment by gatapia** [comment]
Hi @lenak25 I'm still unclear (however date/date range/etc is very hard to visualise for everyone I think).

But I think I understand from your description that this means that the final candle from the exchanges can be a totally arbitrary length.  I.e. If I request it at 00:04:55 it will be a 5 second volume candle.  Lets assume that is correct.  I have also shown that the second last candle (which should always be a full 5 minutes according to my understanding of your description) is totally different from the backtest last candle (which is also a full 5 minutes).

Even if live second  last candle is old (by a few minutes) the values should at least pretend to track along side backtesting data for around the same time but it clearely does not, see final table in my post above, we are getting massive differences in volume for the same approximate time.

Cheers

**Comment by lenak25** [comment]
Hi @gatapia ,

I didn't mean that an exchange gives arbitrary lengths for the last candle, on the contrary: the lengths of the candles are always fixed. When getting data for the bundles, because the data - as you mentioned - organized in 1-min bars, the retrieval is more flexible in the last candle (meaning that for 00:03 you will get a last candle - starting at 00:00 - with a 3 minutes length, while the previous are of 5 minutes length).
But you are talking about an issue you observed in the second last candle, something that we haven't seen. So could you please share some of the code producing those differences so we could try to reproduce?

Thanks,
Lena

**Comment by gatapia** [comment]
Thanks @lenak25,

I log the live data like this:
```
def _handle_data(context, data):
    global symbols
    if symbols is None: symbols = [symbol('%s_%s' % (c, base_currency)) for c in coins]
    try:
        histories = data.history(symbols, ['close', 'volume'], bar_count=2, frequency='5T')
    except:
        return # ignore failed frame (empty candle reported in #236)

    for sym in symbols:
        coin_history = histories.minor_xs(sym)
        # log each of the frames returned (can be 1, 2, or 3 - again reported in #236)
        for row in range(len(coin_history)):
            history_log.info('%s,%d,%s,%s,%s' % (str(data.current_dt), row, sym.symbol, coin_history.close[row], coin_history.volume[row]))    
```

After a day or so I read this data like:
```
live = read_dataframe(filename)
live = live.set_index(pd.to_datetime(live.date)).remove('date')
live_btc = live[live.coin == 'btc_usdt']
# round to the nearest 5 min, will not be exact as backtest but should at least follow same trajectory
live_btc.index = live_btc.index.round('5T')

# history_index is -2 for second last candle and -1 for last candle
live_btc = live_btc.groupby(live_btc.index).nth(history_index).reset_index()           
live_btc.index = live_btc.date
live_btc.remove('date')
```

I have my own csv of the backtest data (saved using a 'minute' backtest).  And the code to get the comparison data is:
```
df = load_csv(exchange, pair)
df = df.set_index(pd.to_datetime(df.date, unit='s'))
df = df.remove(['date', 'open', 'low', 'high'])
date_range = pd.date_range(df.index.min(), df.index.max(), freq='1T')
df = df.reindex(date_range, method='bfill')
# use same resample mechanism as catalyst internals
df = df.resample('5T', closed='left', label='left').agg({'close': 'last', 'volume': 'sum'})
```

Then I compare the data like this:
```
overlapping = set(live_btc.index).intersection(set(backtest_btc.index))

live_ol = live_btc.ix[overlapping]
backtest_ol = backtest_btc.ix[overlapping]

pd.options.display.float_format = '{:,.4f}'.format
compare = live_ol.join(backtest_ol, lsuffix ='_live', rsuffix='_backtest')
compare['close_perc'] = (compare.close_live - compare.close_backtest) / compare.close_live
compare['volume_perc'] = (compare.volume_live - compare.volume_backtest) / compare.volume_live
display(compare)
```
This produces the tables I have above.

Hope that helps

**Comment by gatapia** [comment]
Also @lenak25 can I confirm that backtest `data.current(symbols, ['volume'])` will be changed to return the last 24 hours instead of last `data_frequency` to be inline with what exchanges return (checked polo and bitfinex, they both return 24hr volume when calling `data.current`)?

**Comment by lenak25** [comment]
Hi @gatapia ,

Thanks for the information, I will try to reproduce your issue. On which exchange were you running your code?
Regarding the volume, I will check it.

Thanks,
Lena

**Comment by lenak25** [comment]
Hi @gatapia , 

I have looked at the your code snippets and run some of them.
When you are collecting the live data in this line: `history_log.info('%s,%d,%s,%s,%s' % (str(data.current_dt), row, sym.symbol, coin_history.close[row], coin_history.volume[row]))`
you are taking the information within the `coin_history` dataframe which is already indexed by date (`coin_history.index`) and match to it the current timestamp (`data.current_dt`) which is not the same. I believe that your differences might be a result of this mismatch.

In addition, issue #236 was addressed in develop branch, so you can try to use it to simplify your code.

Thanks,
Lena

**Comment by gatapia** [comment]
you are correct, that's a bug in my code :( I should have logged the row index... and these things take so long to reproduce (log live data and wait for new backtest data to be available). Shame.  I still dont think there should be as much variance 5 / 10 minutes out but I will see if I can build the test data again.

Anyway I have remove volume from my models and the impact was minimal.  I still want to look at 24 hour volume (`data.current('volume')`) as this will allow me to scrap low liquidity coins.  But I will ignore `data.history(volume)` for now.

**Comment by lenak25** [comment]
Thanks @gatapia , I will close this issue after investigating both @brinew27 and yours observations. 
Let me know if you think it should be reopened.
